const adultColouringMeta = {
  farewell: {
    title: 'Farewell',
    year: '2020',
    description: 'An autumn-themed printable colouring page.',
    price: 1,
    original: 'AVAILABLE',
    prints: 'NOTYET',
    buyUrl: 'https://www.etsy.com/ie/listing/859944744/farewell-adult-coloring-printable-page',
    printUrl: '',
    discount: 0,
    discountPrint: 0,
    type: 'adult_colouring',
    subType: 'digital',
    story: 'When leaves are turning yellow and red the swallows are about to leave us once again. These lightning-fast little fellows are true markers of summers days, which we also have to say farewell to when they leave.<br /><br />This design was inspired by these times, when seasons are changing as well as our bird neighbours: winter visitors are arriving, and our summer friends are taking their leaves. The design was made to become a tshirt pattern, but I made it available as an adult colouring page as well.',
  },
  dragon_dance: {
    title: 'Dragon Dance',
    year: '2020',
    description: 'A set of 3 printable colouring pages.',
    price: 8.47,
    original: 'AVAILABLE',
    prints: 'NOTYET',
    buyUrl: 'https://www.etsy.com/ie/listing/838640143/dragon-dance-set-of-3-adult-colouring',
    printUrl: '',
    discount: 20,
    discountPrint: 20,
    merch: [
      {
        name: 'Bookmark Set',
        url: 'https://www.etsy.com/ie/listing/904511925/dragon-dance-paper-bookmark-with-tassel',
        price: 3.50
      },
    ],
    type: 'adult_colouring',
    subType: 'digital',
    story: 'A Draconic Colouring Adventure!<br /><br />Mighty fire-breathers, mystical Eastern spirits and swift water serpents come together for a dance in this set of colouring pages. Are they fighting? Or is there more to it? Give their dragon dance a mood by colouring the enchanted scenes!<br /><br />You can print the pages on either A3 or A4 sized paper (they are optimised for A3, but it will work with smaller scales and US sizes as well). I would suggest using a thicker, non-glossy paper for the best experience.<br /><br />Original artwork was created using acrylic inks on mixed media paper.',
  },
  my_river_dance: {
    title: 'My River Dance',
    year: '2020',
    description: 'A colouring poster for adults in 3 sizes.',
    price: 21.95,
    original: 'AVAILABLE',
    prints: 'NOTYET',
    buyUrl: 'https://www.etsy.com/ie/listing/865606853/my-river-dance-adult-colouring-poster',
    printUrl: '',
    discount: 20,
    discountPrint: 20,
    type: 'adult_colouring',
    story: 'Why stop at a book-sized colouring page? Let\'s colour this giant poster featuring a heron, trouts, splashes of water and a willow tree, inspired by the Irish riversides. The poster is available in 3 sizes: 21×30cm (about A4 size), 30 x 40 cm (about A3 size), and 50 x 70 cm (about A2 size).<br /><br />Paper weight is 192 g/m², which is a decent paper weight for most medium. The poster is suitable for coloured pencils, markers, watercolour pencils, watercolour markers and even watercolour paints if applied with a moderate amount of water. The surface is a smooth matte finish.<br /><br />The artwork was inspired my walks along the beautiful Irish rivers: the Boyne, the Barrow, the Avonmore, and the Royal Canal. Grey herons are common residents along these waters and it\'s always a pleasure to see them hunting for fish. I wanted to capture this essence of the riverside in this picture, a connection to water that is very different from one to the sea.',
  },
};

export default adultColouringMeta;
