const animalArtMeta = {
  sparrowhawk: {
    title: 'Sparrowhawk',
    year: '2020',
    description: 'Ink and watercolour on cold-pressed watercolour paper. 297 x 420 mm ( 11.69 x 16.53 in), 2020.',
    price: 180,
    original: 'SOLD',
    prints: 'NOTYET',
    buyUrl: '',
    printUrl: '',
    discount: 0,
    type: 'watercolour_painting',
    story: 'They say the eyes are the windows to the soul. Look at the eyes of this creature, he couldn\'t even deny his predatory nature! The sparrowhawk, a small bird of prey, but fast, agile and deadly. This one here is a male, which is smaller than the female and has the orange markings. Their skills sparkle most in woodlands, where they cross between the smallest gaps with great speed, and they can chase down prey on foot (?!). Now I\'d love to see THAT!<br /><br />I\'m always so fond of the variety of birds visiting my garden to feed. And it actually never occurred to me that by attracting so many breeds there\'s a consequencial visitor as well... I wasn\'t even aware there are hawks nearby.<br /><br />So I was doing my morning workout and between sets I stared out the kitchen window. Suddenly all the birds took off, and something spiralled down like an arrow. My wandering brain didn\'t even register what was happening, I remember thinking "oh, what kind of bird is this, how interesting" before the shock settled in. "*@$&! He got a sparrow!! Omg! It\'s a hawk!" He sat for 3 seconds in the grass with his prey, then took off. I stood there in complete shock for another minute, thinking I wouldn\'t have stood a chance. By the time I realised what was happening, that sparrow was dead. That\'s how I met my sparrowhawk.',
  },
  the_fishermans_son: {
    title: 'The Fisherman\'s Son (Feathers of Tales IV)',
    year: '2020',
    description: 'Ink and watercolour on acrylic paper. 405 x 508 mm (20 x 16 in), 2020.',
    price: 200,
    original: 'AVAILABLE',
    prints: 'NOTYET',
    buyUrl: 'https://www.etsy.com/ie/listing/827929980/the-fishermans-son-feathers-of-tales-iv',
    printUrl: '',
    discount: 0,
    type: 'watercolour_painting',
    story: '"Well" said the Gruagach "you won\'t see your son to-day. At noon-to-morrow I\'ll put a whistle in my mouth and call together all the birds in my place, and they\'ll come. Among others will be twelve doves. I\'ll put my hand in my pocket, this way, and take out wheat and throw it before them on the ground. The doves will eat the wheat, and you must pick your son out of the twelve. If you find him, you\'ll have him; if you don\'t, you\'ll never have him again." (From "Myths and Folk Tales of Ireland" by Jeremiah Curtin)<br /><br />It wasn\'t easy to pick one tale where the white dove plays a major role, but I chose "The Fisherman\'s Son and The Gruagach of Tricks" because it had these typical folk tale elements in it that everyone knows: a fisherman, a boy, a "man of high degree" as a villain, and magic, and the dove.<br /><br />In the painting I wanted to create that gloomy atmosphere that folk tales have, when you know in the end everyone will live happily ever after, but the story is scary, and the fate of the heroes is to suffer and go through trials. I might not tell you a big spoiler when I say the fisherman will save his boy, but the route to that moment is full of darkness and hardships.<br /><br />This is #4 in my Feathers of Tales series, based on birds of Irish folklore. Fun fact: the model I used is a common grey pigeon you see in every city, but I "bleached" her while painting.',
  },
  one_for_sorrow: {
    title: 'One for Sorrow (Feathers of Tales III)',
    year: '2020',
    description: 'Ink and watercolour on acrylic paper. 405 x 508 mm (20 x 16 in), 2020.',
    price: 450,
    original: 'AVAILABLE',
    prints: 'NOTYET',
    buyUrl: 'https://www.etsy.com/ie/listing/834290581/one-for-sorrow-feathers-of-tales-iii',
    printUrl: '',
    discount: 0,
    type: 'watercolour_painting',
    story: '"One for sorrow,<br />Two for joy,<br />Three for a girl,<br />Four for a boy,<br />Five for silver,<br />Six for gold,<br />Seven for a secret,<br />Never to be told.<br />Eight for a wish,<br />Nine for a kiss,<br />Ten for a bird,<br />You must not miss<br />Eleven is worse<br />Twelve for a dastardly curse."<br /><br />The mischievous magpie. You can hear his unmistakable chatter everywhere, and you may wonder how many you\'ll come across this time? As this nursery rhyme goes, you might get lucky, but what if there\'s only one? Quickly, ask him how his wife is! Then you might have a chance to avoid misfortune.<br /><br />I chose the magpie for this painting because there\'s scarcely any bird with more superstition around it than this black and white fellow. Although magpies have a pretty negative reputation overall, they are quite intelligent and good looking. You can try get rid of them, but they still figure out a way to get what they want, and then their distinctive chatter sounds like laughter. A common bird in every garden, still a real icon. You might be superstitious or not, but you surely know the magpie.<br /><br />This painting is the 3rd in Feathers of Tales, my series on birds of Irish folklore. Previous artworks in the series are "Old Nog" and "The King\'s Friend", both available in my shop.',
  },
  angelic_hunt: {
    title: 'Angelic Hunt',
    year: '2020',
    description: 'Coloured pencils and pen on paper. 420 x 594 mm (16.53 x 23.39 in), 2020.',
    price: 600,
    original: 'AVAILABLE',
    prints: 'NOTYET',
    buyUrl: 'https://www.etsy.com/ie/listing/825365941/angelic-hunt-original-coloured-pencil',
    printUrl: '',
    discount: 0,
    type: 'coloured_pencil_drawing',
    story: 'Little egrets are fascinating. An angelic appearance with the snow white plumage that gently moves in the wind like some kind of jewellery on the bird. Little egrets are never in a hurry, they move with the elegance of a lady. But when you blink, in that second they catch and kill. They are brilliant predators in the skin of an angel.<br /><br />I met the egret serving as my reference for this drawing during one of my walks. She was busy with her catch so I could capture her in a pose that shows the wild in this beautiful bird. The morning breeze on the seashore was lifting the lighter feathers on her body as she turned towards me, holding her fresh kill. That fish reminded me the egret might look like an angel, but she\'s a deadly one.<br /><br />This drawing was created to enter the art competition "Drawn to Nature" hosted by the <a href="https://ukcps.org.uk" title="UK Coloured Pencil Society" target="_blank" rel="noopener noreferrer" >UK Coloured Pencil Society</a>. The objective of the contest was to capture the wildness of nature, which I found in this hunting egret.',
  },
  the_kings_friend: {
    title: 'The King\'s Friend (Feathers of Tales II)',
    year: '2020',
    description: 'Ink and watercolour on watercolour paper. 420 x 594 mm (16.53 x 23.39 in), 2020.',
    price: 600,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/803980602/the-kings-friend-feathers-of-tales-ii',
    printUrl: 'https://www.etsy.com/ie/listing/804085940/the-kings-friend-feathers-of-tales-ii',
    discount: 0,
    type: 'watercolour_painting',
    story: '"You see, the goose used to swim across the lake, and go diving for trout, and catch fish on a Friday for the king, and flew every other day round about the lake, diverting the poor king." from the story <i>King O\'Toole and His Goose</i>.<br /><br />How much time I spent hunting down these timid birds! I was a bit troubled what breed of goose I should choose for the second artwork in my Feathers of Tales project (an art series featuring birds of Irish folklore). I\'d naturally go with one that is resident in Ireland, a true Irish breed. But guess what, most geese are here only for the winter, and they migrate to other places to breed during the summer. So do they count as Irish? And there came the lockdown in the spring, so I had to stick to my closest goose neighbours: the light bellied Brent geese.<br /><br />By the time I finished this painting the last of the Brents left for the summer. But this one will remain here to make me long for the freedom they now have. Geese represent a special kind of freedom and adventure for me thanks to my childhood memories of Nils Holgersson. I wonder if we get back to normal by that time this goose comes back for the winter. Until then here\'s the painting!',
  },
  old_nog: {
    title: 'Old Nog (Feathers of Tales I)',
    year: '2020',
    description: 'Ink and watercolour on watercolour paper. 420 x 594 mm (16.53 x 23.39 in), 2020.',
    price: 600,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/795163346/old-nog-feathers-of-tales-i-original',
    printUrl: 'https://www.etsy.com/ie/listing/803200144/old-nog-feathers-of-tales-i-matte-poster',
    discount: 0,
    type: 'watercolour_painting',
    story: '"And so it was that Old Nog, the wisest heron of the Two Rivers, heard the noise of bubbles breaking on the water as he alighted by the pool side" <i>(from Tarka the Otter by Henry Williamson)</i>.<br /><br />During the lockdown I was restricted to the 2km area of my home, so every Saturday early morning I went for a walk to the nearby seashore at Clontarf to photograph the Brent geese that were still lingering around. I was just about to leave with my legs sore from all the squatting with the camera, when something stirred the Brents, who scattered immediately. And then a big shadow descended: the grey heron arrived. I quickly ducked behind the bushes and grabbed my camera again, just in time to take the photo that served as a reference for this painting.<br /><br />This is the opening artwork for my art series "Feathers of Tales". I chose the heron as the kick-off for this major work because how could you be more majestic than this boss?! With his every slow and measured movement he demands the respect. You see him and you helplessly stop and stare. Elegant and deadly, and a real icon of the Irish waterscapes.',
  },
  deer_in_phoenix_park: {
    title: 'Deer in Phoenix Park',
    year: '2020',
    description: 'Ink and watercolour on mixed media paper. 297 x 420 mm (11.69 x 16.53 in), 2020.',
    price: 225,
    original: 'AVAILABLE',
    prints: 'SOLD',
    buyUrl: 'https://www.etsy.com/ie/listing/813712057/deer-in-phoenix-park-original',
    printUrl: '',
    discount: 0,
    type: 'watercolour_painting',
    story: 'I created this quick study of a stag to practice the deer head for "The Summoning". I ended up liking the linework so much I decided to finish it as a standalone painting.<br /><br />Here in Dublin one of the city attractions is Phoenix Park, an enormous green patch in the city with forests and fields. These deer roam freely, and some of them are pretty friendly towards people (especially if you have some munchies!). They are quite small though, about the size of a pony. Still when you look at them that same grace shines from their posture that you can see with their bigger cousins.',
  },
  peacock_girls: {
    title: 'Peacock Girls',
    year: '2020',
    description: 'Ink and coloured pencil on cartridge paper. 420 x 594 mm (16.53 x 23.39 in), 2020.',
    price: 600,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/813749085/peacock-girls-original-coloured-pencil',
    printUrl: 'https://www.etsy.com/ie/listing/805000568/peacock-girls-bird-art-print-bird-wall',
    discount: 0,
    type: 'coloured_pencil_drawing',
    story: 'Two peahens I captured on camera at Dublin Zoo. The composition is made from two separate photos.<br /><br />The title is wrong on purpose: as a speaker of English as a second language, in my head I tend to simplify English terms and expressions. I always thought of these birds as "girl peacocks" in Hungarian, so I just went with a literal translation when naming this artwork.<br /><br />And why the girls? When you think of this breed, you think of the male. Peacocks are spectacular, colourful, and eye catching. At first sight a peahen doesn\'t look so fascinating, only when you start looking at her closely will you spot the beautiful greenish shine on her plumage and the small orange details on the wings. The peahen\'s look is like a good make up: barely noticeable, but makes all the difference. A worthy pair to the beauty of the peacock.',
  },
  two_geese: {
    title: 'Two Geese',
    year: '2020',
    description: 'Coloured pencil on cartridge paper. 420 x 594 mm (16.53 x 23.39 in), 2020.',
    price: 600,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/795396470/two-geese-original-coloured-pencil',
    printUrl: 'https://www.etsy.com/ie/listing/819493137/two-geese-bird-art-poster-bird-drawing',
    discount: 0,
    type: 'coloured_pencil_drawing',
    story: 'This was my first attempt at coloured pencils, hence my strong linework is missing here, as I was only exploring this medium.<br /><br />While I was working on this drawing I realised I love geese. But why, I wondered. I don\'t know if any readers are familiar with the cartoon <i>Nils Holgersson</i>. When I was a kid I was hooked on the concept of someone going on an adventure on the back of a goose! How cool is that? I believe my thing for geese comes from this childhood experience.',
  },
  hen_and_rooster: {
    title: 'Hen and Rooster',
    year: '2020',
    description: 'Ink and watercolour on cold pressed watercolour paper. 297 x 420 mm (16.53 x 11.69 in), 2020.',
    price: 350,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/813717687/hen-and-rooster-original-watercolour',
    printUrl: 'https://www.etsy.com/ie/listing/804170108/hen-and-rooster-matte-paper-poster',
    discount: 0,
    type: 'watercolour_painting',
    story: 'The source of this painting is two photos I took at the Lisbon Zoo. I wanted to create a vintage feeling with this one, something that really reminds me of country lifestyle.<br /><br />I deliberately put the hen in front, even though roosters tend to be more colourful and decorative. Maybe there was some feminist idea lurking at the back of my head... I only realised later this painting reminds me of <i>American Gothic</i> by Grant Wood. But there the woman is in the background, which I don\'t like! Let\'s give some spotlight to the ladies.',
  },
  rooster_II: {
    title: 'Rooster II',
    year: '2020',
    description: 'Coloured pencil on paper. 210 x 297 mm ( 8.27 x 11.69 in), 2020.',
    price: 150,
    original: 'AVAILABLE',
    prints: 'SOLD',
    buyUrl: 'https://www.etsy.com/ie/listing/799953144/rooster-ii-original-coloured-pencil',
    printUrl: '',
    discount: 0,
    type: 'coloured_pencil_drawing',
    story: 'Another quick practice with coloured pencils. I took the reference photo at a local farm. Whenever I visit such a place I\'m always reminded how much I enjoy these simple animals. You can get me tigers, horses and all kind of majestic beasts, my all time favourites are farm birds!',
  },
  wingspan: {
    title: 'Wingspan',
    year: '2020',
    description: 'Ink and watercolour on acrylic paper. 508 x 405 mm (20 x 16 in), 2020.',
    price: 300,
    original: 'AVAILABLE',
    prints: 'SOLD',
    buyUrl: 'https://www.etsy.com/ie/listing/799976600/wingspan-original-watercolour-painting',
    printUrl: '',
    discount: 0,
    type: 'watercolour_painting',
    story: 'When I was visiting my friend in Manchester, UK, we went to the local park for a walk. I was even thinking of taking my camera, but then I though it wouldn\'t be needed anyway. Of course then we came across a duck pond, which was full of curious Canada geese, and you could guess I had to capture them for reference.<br /><br />So photos were taken with my phone. As a result there were details missing in the image, which I had to fill in from imagination and my existing anatomical knowledge. Most of the details on the wings are from my head, also the way the water splashes around the bathing bird.<br /><br />The goose himself was having a great time, splashing water everywhere around, showing off the giant wings. The Canada goose is one of the largest breeds of geese, almost the size of a mute swan. When those wings are spread, they are huge. That enormous wingspan was the muse for this painting, and even though the reference wasn\'t perfect I felt like I have to paint it anyway.',
  },
  red_pompoms: {
    title: 'Red Pompoms',
    year: '2019',
    description: 'Ink and watercolour on cold-pressed watercolour paper. 210 x 297 mm ( 8.27 x 11.69 in), 2019.',
    price: 200,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/799984894/red-pompoms-original-watercolour',
    printUrl: 'https://www.etsy.com/ie/listing/805998474/red-pompoms-horse-print-horse-portrait',
    discount: 0,
    type: 'watercolour_painting',
    story: 'I was listening to Stephen King\'s <i>The Shining</i> while I was working on this horse portrait. The majority of that story takes place during a harsh winter time, which really made the mark on this piece. The red pompoms break a bit the coolness of the greys and whites, which otherwise would give me the chill.<br /><br />Reference photo I used can be found <a href="https://unsplash.com/photos/Kwb5MOowb9c" title="Red Pompoms watercolour painting reference photo" target="_blank" rel="noopener noreferrer" >here</a>.',
  },
  staring_tiger: {
    title: 'Staring Tiger',
    year: '2019',
    description: 'Ink and watercolour on cold-pressed watercolour paper. 297 x 420 mm ( 16.53 x 11.69 in), 2019.',
    price: 300,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/799992914/staring-tiger-original-watercolour',
    printUrl: 'https://www.etsy.com/ie/listing/819883771/staring-tiger-art-print-animal-portrait',
    discount: 0,
    type: 'watercolour_painting',
    story: 'The tiger at Lisbon Zoo happened to make a performance for us. He was walking back and forth to the observation window, and every time he came close he made a piruette while staring upwards. I managed to take a photo of the attraction, which became the inspiration for this painting.',
  },
  champion: {
    title: 'Champion',
    year: '2019',
    description: 'Ink and watercolour on cold-pressed watercolour paper. 210 x 297 mm ( 8.27 x 11.69 in), 2019.',
    price: 200,
    original: 'SOLD',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/813887321/champion-original-watercolour-painting',
    printUrl: 'https://www.etsy.com/ie/listing/805659122/champion-horse-art-print-horse-portrait',
    discount: 0,
    type: 'watercolour_painting',
    story: 'I used to go horse riding a lot. I never owned a horse though, and most of the time where I went to ride the place wasn\'t posh at all. That was perfect for me of course, I was the kind of rider who didn\'t spend a fortune on proper riding apparel, I was the "don\'t throw that out, it will be good for riding!" kind. And the equipment of the horses for paid classes usually reflected the same, it had the laid-back attitude of casual horse riding.<br /><br />However, once life took me to a place that was quite the opposite. I appeared in my second-chance shoes and fatally ruined shirt that I thought would be ok for riding (if you had tried that you know if you do all the work with the horses you\'ll smell just like them at the end). And everyone else was wearing beautiful jackets and shiny boots, and even the horses were dressed up!<br /><br />Even though that this didn\'t make me feel I belong, I was amazed by the elegance of everything. It was a different world, but a wonderful one. And when I look at the Champion, it brings me back these memories of the amazing beasts in full gear I saw on that day.<br /><br />Reference photo I used can be found <a href="https://unsplash.com/photos/RqC5LCjjfyk" title="Champion watercolour painting reference photo" target="_blank" rel="noopener noreferrer" >here</a>.<br /><br />I donated this picture to <a href="https://www.secondchanceakitarescue.co.uk/" title="Second Chance Akita Rescue" target="_blank" rel="noopener noreferrer" >Second Chance Akita Rescue</a> for their fundraising and it will be available from their website.',
  },
  blondie: {
    title: 'Blondie',
    year: '2019',
    description: 'Ink and watercolour on cold-pressed watercolour paper. 210 x 297 mm ( 8.27 x 11.69 in), 2019.',
    price: 200,
    original: 'SOLD',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/813894449/blondie-original-watercolour-painting',
    printUrl: 'https://www.etsy.com/ie/listing/805654138/blondie-horse-art-print-horse-portrait',
    discount: 0,
    type: 'watercolour_painting',
    story: 'This horse has a really frizzy mane, which I found interesting enough to try to capture it in watercolours.<br /><br />Reference photo I used can be found <a href="https://unsplash.com/photos/xcvMhWJe-qQ" title="Blondie watercolour painting reference photo" target="_blank" rel="noopener noreferrer" >here</a>.<br /><br />I donated this picture to <a href="https://www.secondchanceakitarescue.co.uk/" title="Second Chance Akita Rescue" target="_blank" rel="noopener noreferrer" >Second Chance Akita Rescue</a> for their fundraising and it will be available from their website.',
  },
};

export default animalArtMeta;
