const fantasyArtMeta = {
  the_old_blind_worm_of_the_swamp: {
    title: 'The Old Blind Worm of the Swamp',
    year: '2020',
    description: 'Ink and watercolour on cold pressed watercolour paper. 210 x 297 mm ( 8.27 x 11.69 in), 2020.',
    price: 225,
    original: 'AVAILABLE',
    prints: 'NOTYET',
    buyUrl: 'https://www.etsy.com/ie/listing/799874088/the-old-blind-worm-of-the-swamp-original',
    printUrl: '',
    discount: 0,
    type: 'watercolour_painting',
    story: 'Sometimes I don\'t feel like using reference images. This painting was born on such an occasion, I just started drawing straight on the blank paper, and the result was this little illustration.<br /><br />I imagined a scene as if I was illustrating a fairy tale, where this ancient beast suddenly emerges from the dark water, looking like she has been sleeping down there for hundreds of years. Despite she scared the rider, she meant no harm, on the contrary, she was excited to have a visitor at last!',
  },
  the_climbing_rose_gate: {
    title: 'The Climbing Rose Gate',
    year: '2020',
    description: 'Ink and watercolour on cold pressed watercolour paper. 210 x 297 mm ( 8.27 x 11.69 in), 2020.',
    price: 220,
    original: 'AVAILABLE',
    prints: 'NOTYET',
    buyUrl: 'https://www.etsy.com/ie/listing/813763953/the-climbing-rose-gate-original',
    printUrl: '',
    discount: 0,
    type: 'watercolour_painting',
    story: 'When I work on a larger painting that takes more time to finish I have to take a break from it time to time, and come back with fresh eyes. Usually in these intervals I like to doodle things that don\'t require reference or research, just a blank paper and me. This is how this unicorn started, but it grew so close to my heart by the end that I made her into a finished painting.<br /><br />Maybe that need for a break gave this painting its romantic atmosphere. My favourite flower is the rose, and I wanted to create something really pleasant for me to look at. Like a true dream world. There is a little girl still in me, who likes rainbows and unicorns, and sometimes all she needs is a good old-fashioned fairy tale. She definitely got that when I was painting this artwork.',
  },
  the_summoning: {
    title: 'The Summoning',
    year: '2020',
    description: 'Ink and watercolour on cold pressed watercolour paper. 420 x 594 mm (16.53 x 23.39 in), 2020.',
    price: 650,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/799936804/the-summoning-original-watercolour',
    printUrl: 'https://society6.com/product/the-summoning2790424_print',
    discount: 0,
    type: 'watercolour_painting',
    story: 'Considering the preparations, this painting took me the longest ever to finish. When I had the idea of the subject, I knew I had to go to Phoenix Park to take reference photos of the deer there. But even when I started planning the painting I had no idea about the composition... it all came to life on the paper eventually, no matter how many sketches I made to plan it.<br /><br />I wanted to create a dream-like scene, where some of the details might get lost. So I added a greenish grey wash to create a foggy background. Some quirky elements were also sneaked into the picture, like the eyeball staff of the deer spirit. I really enjoyed drawing such weird things, so I might explore this path a bit more in the future.<br /><br />This is the first painting in a long while where I really ignored outside opinions. To most people the subject is not common and too weird. But this time I let my creativity roam free and just drew and paint whatever occurred to me, not being concerned with feedback. Therefore I would recommend it only to those people who are open to curiosity, who like to meet things they don\'t understand. If you want your guests ask "oh, what is this artwork about?". And you\'re absolutely free to answer whatever you think it is about!',
  },
  the_sunbender: {
    title: 'The Sunbender',
    year: '2020',
    description: 'Ink, watercolour and coloured pencil on mixed media paper. 297 x 420 mm (11.69 x 16.53 in), 2020.',
    price: 320,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/799966694/the-sunbender-original-mixed-media',
    printUrl: 'https://society6.com/product/the-sunbender_print',
    discount: 0,
    type: 'mixed_media_painting',
    story: 'I was on a trip to the UK when the idea of this image came to me. I couldn\'t work on any kind of art while I was away, but I have a deal I made with myself: every day I have to make art in some form, even for just 5 minutes. So I carry my sketchbook around everywhere, and whenever I can\'t be in the studio, I\'m sketching.<br /><br />As usual when I opened the sketchbook to draw I didn\'t really have anything in mind. It was a chore. A promise I have to fulfil even though I don\'t feel like it. And then I looked out the window to see the beautiful springtime Manchester weather as the rain was lashing against the glass. I needed something bright and sparkling.<br /><br />So I imagined a dragon soaring on the sky, but on a colourful sky, the ones you can see after storms and in Disney movies. And I wanted to see a dragon shining through all the remaining darkness. That is how this painting was sketched out. I had everything in mind, and once I got home I started painting.<br /><br />I used a <a href="https://unsplash.com/photos/28ZbKOWiZfs" title="The Sunbender background reference photo" target="_blank" rel="noopener noreferrer" >reference photo</a> for the sky, which I wanted to look carefree with pink clouds.',
  },
  statement: {
    title: 'Statement',
    year: '2020',
    description: 'Ink and coloured pencil on paper. 420 x 297 mm ( 16.53 x 11.69 in), 2020.',
    price: 300,
    original: 'SOLD',
    prints: 'SOLD',
    buyUrl: '',
    printUrl: '',
    discount: 0,
    type: 'mixed_media_painting',
    story: 'This drawing was made to be used as a lead image on my website. I wanted to create an image that looks a bit like as if my inner creativity burst out in some materialised form. My passion for mythical animals like the stag or the eagle, along with the serpent and a unicorn representing the realm of fantasy, which I love. And also the roses, my favourite flowers, that gives a romantic kick to the set.<br /><br />I used several reference photos for this image: <a href="https://unsplash.com/photos/7m_7H0tYFhk" title="Statement: eagle reference photo" target="_blank" rel="noopener noreferrer" >the eagle</a>, <a href="https://unsplash.com/photos/ZDg1IZr0TLg" title="Statement: horse reference photo" target="_blank" rel="noopener noreferrer" >the horse</a>, and <a href="https://images.unsplash.com/photo-1440698662311-f1c775c2ba4a" title="Statement: stag reference photo" target="_blank" rel="noopener noreferrer" >the stag</a>.',
  },
  the_dragon_and_the_kirin: {
    title: 'The Dragon and The Kirin',
    year: '2020',
    description: 'Ink and watercolour on cold pressed watercolour paper. 297 x 420 mm (16.53 x 11.69 in), 2020.',
    price: 300,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/809272187/the-dragon-and-the-kirin-original',
    printUrl: 'https://society6.com/product/the-dragon-and-the-kirin_print',
    discount: 0,
    type: 'watercolour_painting',
    story: 'I played around with a Chinese style dragon concept so much I ended up painting a fighting scene. I wanted to show the dynamic movement and energy of a moment before collision.<br /><br />The story I imagined behind the scene is something like David and Goliath. The confidence of superiority is reflected on the dragon\'s face, while the little kirin is facing the beast with unseen bravery.<br /><br />I didn\'t have a clear idea first how I was going to stage this. When I think of a really dynamic scene like this fighting one, I usually have only a feeling in my head, not the actual concept. I want to show strength! I want to show power! I want the viewer to think "man, this is epic!" These are my guidelines when I start figuring out where that leg should stand, how that arm should bend, and the wiggle of the tail.<br /><br />This is a perfect picture for any anime or fantasy fan, who doesn\'t want to see pretty flowers on their walls. This painting is for people who like action and adventure.',
  },
  morozovas_stag: {
    title: 'Morozova\'s Stag',
    year: '2020',
    description: 'Ink and watercolour on cold pressed watercolour paper. 420 x 297 mm ( 11.69 x 16.53 in), 2020.',
    price: 800,
    original: 'AVAILABLE',
    prints: 'SOLD',
    buyUrl: 'https://www.etsy.com/ie/listing/795402030/morozovas-stag-original-watercolour',
    printUrl: '',
    discount: 0,
    type: 'watercolour_painting',
    story: 'Art inspired by Leigh Bardugo\'s <i>Shadow and bone</i>. Morozova\'s stag was a white magical stag, who was incredibly difficult to track down. When the heroes eventually encountered him, he turned up on a snowy field at night. The little light there was made him look like he was shining in the darkness. I liked the scene so much I wanted to paint it how I saw the scene in my head.',
  },
  reindeer_and_dragonflies: {
    title: 'Reindeer and Dragonflies',
    year: '2020',
    description: 'Coloured pencil on cartridge paper. 297 x 210 mm ( 11.69 x 8.27 in), 2020.',
    price: 150,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/799946282/reindeer-and-dragonflies-original',
    printUrl: 'https://society6.com/product/reindeer-and-dragonflies_print',
    discount: 0,
    type: 'coloured_pencil_drawing',
    story: 'This reindeer started out as a practice how coloured pencil and ink works together. Also I played around with this idea of a deer spirit again. A reindeer was an uncommon breed for me to choose, usually the animals I paint or draw are not that fluffy. But that was the real challenge here.<br /><br />This is one of the first coloured pencil artworks I created. I wasn\'t sure how it will turn out. But the expression of the deer with those warm eyes that balance the freezing cold these animals live in just made me love this drawing in the end. He makes me be aware of the same magic that I aim to capture and show in all my artwork.<br /><br />Reference photo I used for the deer is <a href="https://unsplash.com/photos/34kJZIDqKtw" title="Reindeer and Dragonflies reference photo" target="_blank" rel="noopener noreferrer" >here</a>.',
  },
  grinning_long: {
    title: 'A Grinning Long',
    year: '2019',
    description: 'Pen on cartridge paper. 210 x 297 mm ( 8.27 x 11.69 in), 2019.',
    price: 100,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/814137587/a-grinning-long-original-pen-drawing',
    printUrl: 'https://society6.com/product/a-grinning-long_print',
    discount: 0,
    type: 'ink_drawing',
    story: 'I have a big pile of thin cartridge paper. I got it as part of an artistic birthday present and it was lying around in the studio for a while. I liked the look of it, but it\'s not really watercolour material; the paper is too thin, even the slightest dampness makes horrible curls on it.<br /><br />But I really wanted to create something on that paper, I liked the colour of it, as it instantly gives a vintage look to anything drawn on it. But this stack of paper wasn\'t the only thing I got ages ago and just forgot about it. I also had a pack of coloured fine liner pens, those cheap ones in impossible colours you use at college to highlight the hell out of your notes. Never used them. But now their time had come!<br /><br />I sketched out this wiggling dragon on the paper with a soft pencil, then used the pens to colour it using crossed lines. The technique is very similar to traditional comic book inking, but here I used coloured pens instead of a black one.',
  },
  the_kirin: {
    title: 'The Kirin',
    year: '2019',
    description: 'Ink and watercolour on cold-pressed watercolour paper. 420 x 297 mm ( 11.69 x 16.53 in), 2019.',
    price: 300,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/800259992/the-kirin-original-watercolour-painting',
    printUrl: 'https://society6.com/product/the-kirin2702415_print',
    discount: 0,
    type: 'watercolour_painting',
    story: 'When I was at highschool I had a habit of drawing a kirin for every Chinese new year celebration. I don\'t know where this idea came, probably it just happened a few times that around January I created an artwork featuring a kirin, and this just stuck. A kirin is a beast from Chinese mythology, something like a unicorn. It has the shape of a deer, but has only one horn or antler, and its back is covered with scales.<br /><br />As life went by this tradition became neglected. I wanted to bring it back however, so at the end of 1019 I sat down to plan a painting with a kirin. As usual I had a whole scene in mind, as if it was taken from an animated movie. A beautiful but ancient forest where this magical beast roams.<br /><br />Reference photo I used for the forest is <a href="https://unsplash.com/photos/jFCViYFYcus" title="The Kirin reference photo" target="_blank" rel="noopener noreferrer" >here</a>.',
  },
  unicorn_portrait: {
    title: 'Unicorn Portrait',
    year: '2019',
    description: 'Ink and watercolour on cold-pressed watercolour paper. 210 x 297 mm ( 8.27 x 11.69 in), 2019.',
    price: 120,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/814152973/unicorn-portrait-original-watercolour',
    printUrl: 'https://society6.com/product/unicorn-portrait2702350_print',
    discount: 0,
    type: 'watercolour_painting',
    story: 'When I was a kid, all I drew were dragons. Sometimes I gave a chance to other beasts like unicorns, but my all-time favourite was the dragon. Then I grew up, went to college, started a full-time job, and art, although it never disappeared, went into the background.<br /><br />When it burst out of me again later, I had to find my way back to it, even though I had the urge already to create. I didn\'t really know what an artistic block is, because whenever I didn\'t know what to draw, I went back to my default: dragons. But when I sat down with that empty sheet of paper that eventually became this painting, I faced the dreadful block. I didn\'t feel like drawing anything.<br /><br />I thought about the dragons, as I remembered my default. But no, that time that didn\'t work. And there came the unicorn for the rescue. I thought I would stick to something mythical, and a portrait seemed less an effort. Why not draw a unicorn?<br /><br />So here it is, my artistic un-blocker unicorn portrait.<br /><br />Reference photo I used for the head is <a href="https://unsplash.com/photos/UlAYsmjgauc" title="Unicorn Portrait reference photo" target="_blank" rel="noopener noreferrer" >here</a>.',
  },
  csodaszarvas: {
    title: 'Csodaszarvas',
    year: '2019',
    description: 'Ink and watercolour on cold-pressed watercolour paper. 420 x 297 mm (16.53 x 11.69 in), 2019.',
    price: 350,
    original: 'AVAILABLE',
    prints: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/814147401/csodaszarvas-magic-stag-original',
    printUrl: 'https://society6.com/product/csodaszarvas-white-stag_print',
    discount: 0,
    type: 'watercolour_painting',
    story: 'Once on a hiking trip we came across a part of a forest where the sun was breaking through the leaves. I was wearing my sunglasses and stopped because the view looked just like a story book illustration. But when I took off my sunglasses to take a photo I got a bit disappointed. It didn\'t look as magical any more, not without the filter.<br /><br />So I shot through my sunglasses. I put one side of it in front of the camera lenses, and there I had exactly the right colour on my image.<br /><br />But this was only a landscape, and I wanted something to HAPPEN there. I thought why not add some Hungarian mythology to it this time? The white stag plays an important role in the myths of the origins of Hungarians. According to the legends our ancestors chased a white stag to hunt him down, but the stag lead them to their future wives. So that was the beginning of our people, ancestors of the two hunters. Being Hungarian this story is part of me as well.',
  },
};

export default fantasyArtMeta;
