const merchandiseMeta = {
  swans_of_ireland_2021_bookmark: {
    title: 'Swans of Ireland Bookmark Set',
    year: '2021',
    description: 'Set of 3 paper bookmarks with tassel and rose charm.',
    price: 3.50,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/964814293/swans-of-ireland-paper-bookmark-with',
    discount: 0,
    type: 'merchandise',
  },
  low_tide_tale_2021_greeting_card: {
    title: 'Low Tide Tale Greeting Card',
    year: '2021',
    description: 'Greeting card with white envelope.',
    price: 3.50,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/953617477/low-tide-tale-greeting-card-with',
    discount: 0,
    type: 'merchandise',
  },
  greeting_cards_2021_spring: {
    title: 'Birds in Love Greeting Cards',
    year: '2021',
    description: 'Greeting cards with white envelopes.',
    price: 3.50,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/943508801/birds-in-love-greeting-card-set-songbird',
    discount: 0,
    type: 'merchandise',
  },
  postcards_2021_spring: {
    title: 'Birds in Love Postcard set',
    year: '2021',
    description: 'Set of 3 postcards with bird pair prints.',
    price: 5,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/928314268/birds-in-love-postcard-set-songbird',
    discount: 0,
    type: 'merchandise',
  },
  buttercups_2021_unisex_tee: {
    title: 'Buttercups Unisex Tee',
    year: '2021',
    description: 'Unisex short sleeved t-shirt with a robin pair print.',
    price: 32,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/941546699/buttercups-unisex-short-sleeve-t-shirt',
    discount: 0,
    type: 'merchandise',
  },
  sandworts_2020_unisex_tee: {
    title: 'Sandworts Unisex Tee',
    year: '2020',
    description: 'Unisex short sleeved t-shirt with a blue tit pair print.',
    price: 32.50,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/941546297/sandworts-unisex-short-sleeve-t-shirt',
    discount: 0,
    type: 'merchandise',
  },
  cuckooflowers_2020_unisex_tee: {
    title: 'Cuckooflowers Unisex Tee',
    year: '2020',
    description: 'Unisex short sleeved t-shirt with a grey heron pair print.',
    price: 34.50,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/941545811/cuckooflowers-unisex-short-sleeve-t',
    discount: 0,
    type: 'merchandise',
  },
  sparrowhawk_2020_notebook: {
    title: 'Sparrowhawk Artist\'s Notebook',
    year: '2020',
    description: 'Artist\'s spiral notebook with blank pages for sketching.',
    price: 20.95,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/911212429/sparrowhawk-artists-notebook-spiral',
    discount: 0,
    type: 'merchandise',
  },
  alfalfa_2020_womens_tee: {
    title: 'Alfalfa Women\'s Short Sleeved Tee',
    year: '2020',
    description: 'Short sleeved women\'s fit t-shirt with my artwork "Farewell" printed on it.',
    price: 32,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/906857911/alfalfa-womens-short-sleeve-t-shirt-with',
    discount: 0,
    type: 'merchandise',
  },
  dragon_dance_2020_bookmark: {
    title: 'Dragon Dance Bookmark Set',
    year: '2020',
    description: 'Set of 3 paper bookmarks with tassel and feather charm.',
    price: 3.50,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/904511925/dragon-dance-paper-bookmark-with-tassel',
    discount: 0,
    type: 'merchandise',
  },
  sparrowhawk_2020_magnet: {
    title: 'Sparrowhawk Fridge Magnet',
    year: '2020',
    description: 'Rectangular, 78x53 mm fridge magnet with my "Sparrowhawk" watercolour printed on it.',
    price: 5.15,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/882191122/sparrowhawk-fridge-magnet-watercolour',
    discount: 0,
    type: 'merchandise',
  },
  farewell_2020_notebook: {
    title: 'Farewell Hardcover Notebook',
    year: '2020',
    description: 'Hardcover, blank notebook with "Farewell" printed on the front. Orange colouring on edges and matching rubber band to secure cover.',
    price: 14.95,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/895826951/farewell-hardcover-journal-bird-art',
    discount: 0,
    type: 'merchandise',
  },
  xmas_cards_2020_6set: {
    title: 'Christmas Card set',
    year: '2020',
    description: 'Set of 6 or 3 Christmas cards with robin and tit prints, with gold envelopes.',
    price: 8,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/891942385/robins-and-tits-greeting-card-set',
    discount: 0,
    type: 'merchandise',
  },
  rascals_2020_sketchbook: {
    title: 'Rascals Artist\'s Sketchbook',
    year: '2020',
    description: 'Soft cover, spiral bound artist\'s sketchbook with 48 blank pages (260gsm).',
    price: 23,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/888840913/rascals-artists-sketchbook-spiral',
    discount: 0,
    type: 'merchandise',
  },
  rascals_2020_mens_tee: {
    title: 'Rascals Men\'s Short Sleeved Tee',
    year: '2020',
    description: 'Short sleeved men\'s or unisex t-shirt with my artwork "Rascals" printed on it.',
    price: 31.50,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/875381994/rascals-mens-short-sleeve-t-shirt-with',
    discount: 0,
    type: 'merchandise',
  },
  rascals_2020_womens_tee: {
    title: 'Rascals Women\'s Short Sleeved Tee',
    year: '2020',
    description: 'Short sleeved women\'s fit t-shirt with my artwork "Rascals" printed on it.',
    price: 32,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/889316355/rascals-womens-short-sleeve-t-shirt-with',
    discount: 0,
    type: 'merchandise',
  },
  farewell_2020_mens_tee: {
    title: 'Farewell Men\'s Short Sleeved Tee',
    year: '2020',
    description: 'Short sleeved men\'s or unisex t-shirt with my artwork "Farewell" printed on it.',
    price: 28.50,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/875079870/farewell-mens-short-sleeve-t-shirt-with',
    discount: 0,
    type: 'merchandise',
  },
  farewell_2020_womens_tee: {
    title: 'Farewell Women\'s Short Sleeved Tee',
    year: '2020',
    description: 'Short sleeved women\'s fit t-shirt with my artwork "Farewell" printed on it.',
    price: 28,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/864817848/farewell-womens-short-sleeve-t-shirt',
    discount: 0,
    type: 'merchandise',
  },
};

export default merchandiseMeta;
