const merchandiseMeta = {
  sparrowhawk_2020_magnet: {
    title: 'Sparrowhawk Fridge Magnet',
    year: '2020',
    description: 'Rectangular, 78x53 mm fridge magnet with my "Sparrowhawk" watercolour printed on it.',
    price: 5.15,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/882191122/sparrowhawk-fridge-magnet-watercolour',
    discount: 0,
    type: 'merchandise',
  },
  farewell_2020_notebook: {
    title: 'Farewell Hardcover Notebook',
    year: '2020',
    description: 'Hardcover, blank notebook with "Farewell" printed on the front. Orange colouring on edges and matching rubber band to secure cover.',
    price: 14.95,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/895826951/farewell-hardcover-journal-bird-art',
    discount: 0,
    type: 'merchandise',
  },
  xmas_cards_2020_6set: {
    title: 'Christmas Card set',
    year: '2020',
    description: 'Set of 6 or 3 Christmas cards with robin and tit prints, with gold envelopes.',
    price: 8,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/891942385/robins-and-tits-greeting-card-set',
    discount: 0,
    type: 'merchandise',
  },
  rascals_2020_sketchbook: {
    title: 'Rascals Artist\'s Sketchbook',
    year: '2020',
    description: 'Soft cover, spiral bound artist\'s sketchbook with 48 blank pages (260gsm).',
    price: 23,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/888840913/rascals-artists-sketchbook-spiral',
    discount: 0,
    type: 'merchandise',
  },
  rascals_2020_mens_tee: {
    title: 'Rascals Men\'s Short Sleeved Tee',
    year: '2020',
    description: 'Short sleeved men\'s or unisex t-shirt with my artwork "Rascals" printed on it.',
    price: 31.50,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/875381994/rascals-mens-short-sleeve-t-shirt-with',
    discount: 0,
    type: 'merchandise',
  },
  rascals_2020_womens_tee: {
    title: 'Rascals Women\'s Short Sleeved Tee',
    year: '2020',
    description: 'Short sleeved women\'s fit t-shirt with my artwork "Rascals" printed on it.',
    price: 32,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/889316355/rascals-womens-short-sleeve-t-shirt-with',
    discount: 0,
    type: 'merchandise',
  },
  farewell_2020_mens_tee: {
    title: 'Farewell Men\'s Short Sleeved Tee',
    year: '2020',
    description: 'Short sleeved men\'s or unisex t-shirt with my artwork "Farewell" printed on it.',
    price: 28.50,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/875079870/farewell-mens-short-sleeve-t-shirt-with',
    discount: 0,
    type: 'merchandise',
  },
  farewell_2020_womens_tee: {
    title: 'Farewell Women\'s Short Sleeved Tee',
    year: '2020',
    description: 'Short sleeved women\'s fit t-shirt with my artwork "Farewell" printed on it.',
    price: 28,
    original: 'AVAILABLE',
    buyUrl: 'https://www.etsy.com/ie/listing/864817848/farewell-womens-short-sleeve-t-shirt',
    discount: 0,
    type: 'merchandise',
  },
};

export default merchandiseMeta;
